### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by ZSenZhang** [CAIDA/libipmeta#26]
When I was installing the libipmeta, I followed up the guide to the last three command: ./build_latest.sh, but I got the 
$ ./build_latest.sh
-bash: ./build_latest.sh: No such file or directory
And I did not find the build_latest.sh file on the github. I wonder if there is anything wrong happened here?

**Comment by markzz** [comment]
Try running `./autogen.sh` instead because `./build_latest.sh` is not in the project's files.

**Comment by ZSenZhang** [comment]
Thanks, but still get error with ./autogen.sh:
$ ./autogen.sh 
Initializing submodules
Running autoconf
./autogen.sh: line 5: autoreconf: command not found

Do I do something wrong?

**Comment by salcock** [comment]
You'll need to install the autoconf, automake and libtool packages for your system.

If you're on Debian or Ubuntu, try:

    sudo apt-get install automake autoconf libtool

Then try running `./autogen.sh` again.

**Comment by markzz** [comment]
You should try installing build-essential in Debian or Ubuntu if you haven't already.

```sudo apt install build-essential```

**Comment by ZSenZhang** [comment]
Thanks guys! I have installed all of the tools that you mentioned and ran `./autogen.sh` and got the following result:
```
Initializing submodules
Running autoconf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in '..'.
libtoolize: copying file '../ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:46: installing '../compile'
configure.ac:28: installing '../missing'
common/Makefile.am: installing '../depcomp'
autoreconf: Leaving directory `.'
```

Is that correct? If so when I ran `sudo make install` I got failure result as:
```
$ sudo make install
make: *** No rule to make target 'install'.  Stop.
```

Wonder why that will happen.

**Comment by markzz** [comment]
Did you run `./configure`?

**Comment by markzz** [comment]
I can confirm that the following builds and installs this software:

```
$ ./autogen.sh
$ ./configure
$ make
# make install
```

**Comment by ZSenZhang** [comment]
Sooooo Coooool! Thanks a lot for your help! Last stupid question, how can we run the `libipmeta`. Because after installation when I ran `libipmeta` it still said `libipmeta: command not found`  😅

**Comment by markzz** [comment]
`libipmeta` is a C library, you must include this in your own C code when you wish to use the library. There is an included `ipmeta-lookup` tool that uses this library that you can use.

**Comment by ZSenZhang** [comment]
Get it! Thanks again!
